USE presensipander_db;

CREATE TABLE IF NOT EXISTS siswa (
    id INT AUTO_INCREMENT PRIMARY KEY,
    noInduk VARCHAR(20) NOT NULL UNIQUE,
    nisn VARCHAR(20) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    tglLahir DATE DEFAULT NULL,
    kota VARCHAR(50) DEFAULT NULL,
    alamat TEXT DEFAULT NULL,
    namaAyah VARCHAR(100) DEFAULT NULL,
    pekerjaanAyah VARCHAR(50) DEFAULT NULL,
    namaIbu VARCHAR(100) DEFAULT NULL,
    pekerjaanIbu VARCHAR(50) DEFAULT NULL,
    cls VARCHAR(20) NOT NULL,
    parent VARCHAR(100) DEFAULT NULL,
    wa VARCHAR(20) DEFAULT NULL,
    status VARCHAR(20) DEFAULT 'ok',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS mapel (
    id INT AUTO_INCREMENT PRIMARY KEY,
    code VARCHAR(20) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    grade VARCHAR(20) NOT NULL,
    hours INT DEFAULT 0,
    cat VARCHAR(50) DEFAULT 'Umum',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS kelas (
    id INT AUTO_INCREMENT PRIMARY KEY,
    grade VARCHAR(20) NOT NULL,
    name VARCHAR(50) NOT NULL UNIQUE,
    teacher VARCHAR(100) DEFAULT NULL,
    count INT DEFAULT 0,
    status VARCHAR(20) DEFAULT 'Aman',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- OPTIONAL: Masukkan data dummy jika diperlukan
-- INSERT INTO siswa (...) VALUES (...);
-- INSERT INTO mapel (...) VALUES (...);
-- INSERT INTO kelas (...) VALUES (...);
